[package]
name = "build-debugger-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
addr2line = "0.24.2"
anyhow = "1.0.95"
nix = { version = "0.29.0", features = ["process", "ptrace"] }
rustyline = "15.0.0"
